# Generated by Django 4.0 on 2022-03-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_inentory_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inentory',
            new_name='inventory',
        ),
    ]
